
---

- name: Update all servers
  hosts: all
  become: yes
  tasks:
    - name: Install updates (CentOS)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
      register: apt_result
      retries: 5
      delay: 30
      until: apt_result is succeeded

- name: Install Apache and PHP on web servers
  hosts: web_servers
  become: true
  vars:
    apache_package: "{{ 'apache2' if ansible_distribution == 'Ubuntu' else 'httpd' }}"
    php_package: php

  tasks:
    - name: Install Apache and PHP
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest

